# APPLICATION LEVEL

## DEFAULT CONFIG
spring:
  application:
    name: demo-for-spring2
server:
  port: 8999

## LOGGING
logging:
  level:
#    root: ERROR
    org:
      springframework:
        web: ERROR
        boot:
          actuate: ERROR

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

default:
  hello:
    name: God


# ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: '*'

---

spring:
  profiles: discovery

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true